inherit: true
checks:
    php: true
filter:
    excluded_paths:
        - Resources/*
        - tests/*
        - vendor/*
        - src/Sphinx/sphinxapi.php

#Doc: https://scrutinizer-ci.com/docs/configuration/build
