sudo: false
language: php
os:
  - linux
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
before_script:
  - composer self-update
  - composer install --prefer-dist
script: vendor/bin/phpunit
notifications:
  email: false
